[custom]

;设置分组标志位
custom_proxy_group=自动选择`url-test`[]日本节点`[]台湾节点`[]香港节点`[]美国节点`http://www.gstatic.com/generate_204`20,5,200
custom_proxy_group=日本节点`fallback`(日本)`http://www.gstatic.com/generate_204`20,5
custom_proxy_group=台湾节点`fallback`(台湾)`http://www.gstatic.com/generate_204`20,5
custom_proxy_group=香港节点`fallback`(香港)`http://www.gstatic.com/generate_204`20,5
custom_proxy_group=美国节点`fallback`(美国)`http://www.gstatic.com/generate_204`20,5
custom_proxy_group=低倍率节点`fallback`(^x0\.[1-9]$)`http://www.gstatic.com/generate_204`20,5
custom_proxy_group=OpenAI`fallback`[]美国节点`http://www.gstatic.com/generate_204`20,5
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/cutethotw/ClashRule/main/GeneralClashConfig.yml
