[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则-在线更新版

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：不支持
;增强国外GFW：不支持


; ================= 代理分组 (Proxy Group) =================

; 1、智能切换 (最低延迟url-test，嵌套日/港/台分组，频率30秒，超时默认，容忍度300ms)
custom_proxy_group=智能切换`url-test`[]日本节点分组`[]香港节点分组`[]台湾节点分组`http://www.gstatic.com/generate_204`30,,300

; 2、ZProxy (最低延迟url-test，包含所有节点 .* ，频率30秒，超时默认，容忍度300ms)
custom_proxy_group=ZProxy`url-test`.*`http://www.gstatic.com/generate_204`30,,300

; 3、美国节点分组 (故障切换fallback，频率30秒，正则匹配多种美国节点常见命名)
custom_proxy_group=美国节点分组`fallback`(?i)(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.gstatic.com/generate_204`30

; 4、香港节点分组 (故障切换fallback，频率30秒)
custom_proxy_group=香港节点分组`fallback`(?i)(港|HK|Hong Kong)`http://www.gstatic.com/generate_204`30

; 5、日本节点分组 (故障切换fallback，频率30秒)
custom_proxy_group=日本节点分组`fallback`(?i)(日|东京|大阪|JP|Japan)`http://www.gstatic.com/generate_204`30

; 6、台湾节点分组 (故障切换fallback，频率30秒)
custom_proxy_group=台湾节点分组`fallback`(?i)(台|新北|彰化|TW|Taiwan)`http://www.gstatic.com/generate_204`30

; 7、低倍率节点分组 (故障切换fallback，频率30秒，正则精确匹配包含 x0.1 到 x0.9 字符的节点)
custom_proxy_group=低倍率节点分组`fallback`(?i)[xX]0\.[1-9]`http://www.gstatic.com/generate_204`30

; 8、OpenAI节点分组 (故障切换fallback，频率30秒，只嵌套台湾节点分组)
custom_proxy_group=OpenAI节点分组`fallback`
